---
title: "What is IEEE IRDS?"
format:
  revealjs:
    theme: simple
    slide-number: true
    transition: fade
bibliography: "../../bibliography/2026-ICE.bib"
---

## IEEE IRDS
By expert representatives from global semiconductor manufacturers and related experts, the Institute of Electrical and Electronics Engineers (IEEE) **International Roadmap for Devices and Systems (IRDS)** establishes a comprehensive strategic framework for advanced hardware acceleration, microelectronics, and computing systems. 

It represents a collective multi-stakeholder consensus engineered by expert representatives from _global semiconductor manufacturers, original equipment manufacturers (OEMs), materials suppliers, and analytical research laboratories_. 

## Many Roadmaps?

Ultimately, the roadmaps operate as the definitive technological baselines for many aspects of semidconductor manufacturing.  They are thus useful for  **evaluating modern fabrication capabilities**[@Ang-2026-ID-286] and **guiding scaling trajectories within global value chains**[@Liao-2026-ICE-DCE].

## EEE IRDS ESHS
Focusing on sustainability on and around the **semiconductor facilities**, the **Environment, Safety, Health & Sustainability (ESHS)** chapter of the roadmap defines quantitative benchmarks and actionable targets for building climate-resilient fabrication facilities[@Liao-2026-ICE-DCE][@Ang-2026-ID-286]. 

Grounded in facility-monitoring, it outlines critical tracking metrics including freshwater usage, evaporative water losses, hazardous waste generation, and energy consumption factors. However, contemporary reviews identify ongoing technology gaps within the roadmap, particularly regarding real-time chemical intensity tracking, Scope 1 greenhouse gas tool abatement, and Scope 3 supply-chain footprint blind spots.

## ESHS as Sites of Practice

Semiconductor facilities become important sites of practice and research for smart sustainable manufacturing to integrate best Industry 5.0 with advanced RegTech and FinTech [@Ang-2026-ID-286; @Liao-2026-ID-372].

- Maps directly to the Twin Green & Digital Transition.
- Bridges factory-floor operational data with macro ESG frameworks.

## See Also: Semi Standards - 1

The IRDS framework explicitly cross-references established [SEMI standards](https://www.semi.org/en/products-services/standards/using-semi-standards) to govern manufacturing sustainability metrics, particularly leveraging the **SEMI S** Series (Safety, Environmental & Energy) to calculate Equivalent Energy Consumption Factors [@Liao-2026-ICE-DCE]. 

## See Also: Semi Standards - 2

This coordination establishes unified financial and environmental benchmarking metrics, allowing technology managers to balance tool-level operational constraints with localized utility realities.

Other relevant SEMI standards consists of **SEMI MF** Series (Metrology), **SEMI T** Series (Traceability) and **SEMI F** Series (Facilities). Also **SEMI MS** Series and **SEMI C** Series can have specific material flow requirements for the **SEMI M** Series (Wafers & Process Control) to implement a System of Systems (SoS) orchestration.

## References

::: {#refs}
:::