editorial_carbon_neutrality:
  title: Peer Reviewers, mostly Q1 and Q2 journals,  
  location: Editorial 
  date: 2021 — Present
  description: Completed 20+ peer reviews, especially on AI and Industry 4.0. #link("http://hanteng.sapiens.cv/assets/certificates/2026/Reviewer_Certificate_23_May_2026.pdf")[Scientific Reports (Q1:2)]; Financial Innovation (Q1:2); Nature #link("http://hanteng.sapiens.cv/assets/certificates/2026/Reviewer_Certificate_13_May_2026.pdf")[Humanities and Social Sciences Communications] (Q1:1); Politics and Governance (Q2:1), Frontiers in Public Health (Q1:1); Journal of Clinical Epidemiology (Q1:1); Heliyon (Q1:2); Cogent Economics & Finance (Q1:1); Cogent Education (Q2:1); Future Internet (Q2:1); #link("http://hanteng.sapiens.cv/assets/certificates/2026/Reviewer_Certificate_17_April_2026.pdf")[Discover Artificial Intelligence] (1); Sustainability (Q2:4); Applied Economics Letters (Q3:1); Environment Systems and Decisions (1);
ieee_carbon_neutrality:
  title: TC Member, #link("https://ieeesystemscouncil.org/technical-committee/joint-isetems-tc-carbon-neutrality-technical-committee")[Joint IEEE Systems Engineering/TEMS TC on Carbon Neutrality]
  location: Technical
  date: 2026 — Present
  description: Explore active research and strategies to promote carbon neutrality best practices, including surveying liaisons with other IEEE TCs, and other international organizations.
itu_standardization:
  title: Expert Contributor
  location: International Telecommunication Union (ITU-T)
  date: 2023 - 2024
  description: Focus Group on AI for Agriculture (FG-AI4A)
  details:
    - Authored technical input document b-FG-AI4A-I-132 on linking carbon accounting data with agricultural business and products.
    - Successfully integrated the framework into global standard ITU-T Y.Suppl.83 (07/2024) under Section 7.2.7 (TG-Digital Agri-Finance).
    - Operationalized 'Carbon Information Chains' to translate regional standards into international functional requirements.
ieee_leadership:
  title: Student Branch Development & Launch
  location: Guangzhou, China
  date: 2019 - 2023
  description: IEEE Technology and Engineering Management Society (TEMS)
  details:
    - Orchestrated and managed the establishment of the IEEE TEMS Student Branch during tenure as Center Director.